/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ROBOT_R = 6;
  /** RegularExpression Id. */
  int VARS = 7;
  /** RegularExpression Id. */
  int PROCS = 8;
  /** RegularExpression Id. */
  int assignTo = 9;
  /** RegularExpression Id. */
  int goTo = 10;
  /** RegularExpression Id. */
  int move = 11;
  /** RegularExpression Id. */
  int turn = 12;
  /** RegularExpression Id. */
  int face = 13;
  /** RegularExpression Id. */
  int put = 14;
  /** RegularExpression Id. */
  int pick = 15;
  /** RegularExpression Id. */
  int moveToThe = 16;
  /** RegularExpression Id. */
  int moveInDir = 17;
  /** RegularExpression Id. */
  int jumpToThe = 18;
  /** RegularExpression Id. */
  int jumpInDir = 19;
  /** RegularExpression Id. */
  int nop = 20;
  /** RegularExpression Id. */
  int IF = 21;
  /** RegularExpression Id. */
  int THEN = 22;
  /** RegularExpression Id. */
  int ELSE = 23;
  /** RegularExpression Id. */
  int WHILE = 24;
  /** RegularExpression Id. */
  int DO = 25;
  /** RegularExpression Id. */
  int REPEAT = 26;
  /** RegularExpression Id. */
  int facing = 27;
  /** RegularExpression Id. */
  int canPut = 28;
  /** RegularExpression Id. */
  int canPick = 29;
  /** RegularExpression Id. */
  int canMoveInDir = 30;
  /** RegularExpression Id. */
  int canJumpInDir = 31;
  /** RegularExpression Id. */
  int canMoveToThe = 32;
  /** RegularExpression Id. */
  int canJumpToThe = 33;
  /** RegularExpression Id. */
  int not = 34;
  /** RegularExpression Id. */
  int O_BRACKET = 35;
  /** RegularExpression Id. */
  int C_BRACKET = 36;
  /** RegularExpression Id. */
  int COMMA = 37;
  /** RegularExpression Id. */
  int COLON = 38;
  /** RegularExpression Id. */
  int SEMICOLON = 39;
  /** RegularExpression Id. */
  int V_BAR = 40;
  /** RegularExpression Id. */
  int VARIABLE = 41;
  /** RegularExpression Id. */
  int NUMBER = 42;
  /** RegularExpression Id. */
  int NAME = 43;
  /** RegularExpression Id. */
  int TURN_DIR = 44;
  /** RegularExpression Id. */
  int ORIENTATION = 45;
  /** RegularExpression Id. */
  int X_OBJECT = 46;
  /** RegularExpression Id. */
  int DIRECTION = 47;
  /** RegularExpression Id. */
  int ALPHANUM = 48;
  /** RegularExpression Id. */
  int LETTER = 49;
  /** RegularExpression Id. */
  int DIGIT = 50;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\f\"",
    "\"robot_r\"",
    "\"vars\"",
    "\"procs\"",
    "\"assignto\"",
    "\"goto\"",
    "\"move\"",
    "\"turn\"",
    "\"face\"",
    "\"put\"",
    "\"pick\"",
    "\"movetothe\"",
    "\"moveindir\"",
    "\"jumptothe\"",
    "\"jumpindir\"",
    "\"nop\"",
    "\"if\"",
    "\"then\"",
    "\"else\"",
    "\"while\"",
    "\"do\"",
    "\"repeat\"",
    "\"facing\"",
    "\"canput\"",
    "\"canpick\"",
    "\"canmoveindir\"",
    "\"canjumpindir\"",
    "\"canmovetothe\"",
    "\"canjumptothe\"",
    "\"not\"",
    "\"[\"",
    "\"]\"",
    "\",\"",
    "\":\"",
    "\";\"",
    "\"|\"",
    "<VARIABLE>",
    "<NUMBER>",
    "<NAME>",
    "<TURN_DIR>",
    "<ORIENTATION>",
    "<X_OBJECT>",
    "<DIRECTION>",
    "<ALPHANUM>",
    "<LETTER>",
    "<DIGIT>",
  };

}
